[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cmds = ["npm ci --legacy-peer-deps --ignore-scripts && cd backend && npm ci --legacy-peer-deps --ignore-scripts && cd .. && ./build-railway.sh"]

[start]
cmd = "npm run start:production"

[variables]
NODE_OPTIONS = "--max-old-space-size=2048"
