-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "avg_daily_sales_30d" DECIMAL(8,2) DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "days_to_zero" INTEGER DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "last_purchase_date" TIMESTAMP(3);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "recommended_qty" INTEGER DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "trend" TEXT DEFAULT 'STABLE';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "in_transit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "delivery_days" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "min_stock" INTEGER NOT NULL DEFAULT 5;
